var GAME_LEVELS = [
  ["                                                                                                                         ",
   "                                                                                                                         ",
   "                                                                                                                         ",
   "                                                                                                                         ",
   "                                                          xxxxxxxxxxxx                                                   ",
   "                                                        x      o       x                                                 ",
   "                                                       x       o        x                                                ",
   "                                                        x    xxxxxx    x                                                 ",
   "                                                        x              x                                                 ",
   "                                                           x       xxxxxx                                                ",
   "                                                                                                                         ",
   "    xxxxxx                                               xxxx                                                            ",
   "  xxx                                                                                                                f   ",
   "  x                                                 xxxx                                                                 ",
   "  x       @            p                      p                                                                          ",
   "  x     xxxxx      xxxxxxxxx                xxxxxx            xxxxxxxxx       o  o                     o                 ",
   "  x                x       x          o o o x    xxxx                       xxxxxxx                           o          ",
   "  xxxx         xxxxx      xxxxxyyyyyxxxxxxxx       x                                    xxxxyyyxxx   xxxx  xxxxxxxxxxxxx ",
   "     x                   xxx                       x                                 xxx                                 ",
   "     x        o o o   xxx                          x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxx                                    ",
   "     xxx   xxxxxxxxxxxxx                            x!!!!!!!!!!!!!!!!!!!!!!!!!!!xxx                                      ",
   "                                                    xxxxxxxx!!!!!!!!!!!!!!!xxxxxxx                                       ",
   "                                                           x!!!!!!!!!!!!!!!x                                             ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
   ["                                                                                                               ",
    "                                                                                                               ",
    "                                                                                                               ",
    "                                                                                                               ",
    "                                                                                                               ",
    "                                                        o                 o                                    ",
    "                                                        o                xxxx!!!!!!!xxxx                       ",
    "                                            xxxxxxxxxxxxxxxxxxxx            xxx!!!xxx                          ",
    "   @                                        xxxxxxxxxxxxxxxxxxxx              x!!!x                            ",
    "xxxxxxxx                               xxxxxxxxxxxxxxxxxxxxxxxxxx               v                              ",
    "        xxxxx                               xxxxxxxxxxxxxxxxxxxxxxxx                                           ",
    "           xxxxxx           xxxxxx                                                                             ",
    "               xxxxxx                                                                                          ",
    "                   xxxxxxx  o                                              o                                   ",
    "                         xxxxxxx o                                      xxxxx!!!!!!!!xxxxx                     ",
    "                               xxxxx    o                                   x!!!!!!!!x                         ",
    "                                   xxyyyy                                   xxxxxxxxxx                         ",
    "                                        xxxxxx                                                                 ",
    "                                             xxxxxx                                                            ",
    "                                                  xxxxxx                                                       ",
    "                                                       xxxxx                                                   ",
    "                                                           xxyyyyyyyyyxxxx                                     ",
    "                                                                                                               ",
    "       xxx                                                     xx                                              ",
    "       xyy =                                                      o   x                                        ",
    "       xyy                                                        o   x                                        ",
    "       xyy =                                                 xxxxxxxxxx                                        ",
    "       xxx                                                yyyyy             f                                  ",
    "                                                      xxxxx                                                    ",
    "                                                  xxxxx                                                        ",
    "                                              xxxxx                                                            ",
    "                               o          yyyyy                                                                ",
    "                               o      xxxxx                         xxxxxxxxxxxxxx                             ",
    "                            xxxxxxxxxxx                             y            x                             ",
    "                                                                    y      o     x                             ",
    "                                                        p           y      o     x                             ",
    "                   xxxxxxx                     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                             ",
    "                                               x                                                               ",
    "                                    p          x                                                               ",
    "xxxxxxxxxxxxxxxxxxxx      xxxxxxxxxxxxxxxxxxxxxx                                                               ",
    "                   x!!!!!!x                                                                                    ",
    "                   x!!!!!!x                                                                                    ",
    "                   x!!!!!!x                                                                                    ",
    "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
    ["                                 xxxxxxxxxxx                                                                                              ",
    "                                  x!!!!!!!!!   =                                                                                           ",
    "                                  x!!!!!!!!!                 o                                                                             ",
    "                                  x!!!!!!!!!   =             o                                                           xxxxxxxxxx        ",
    "                                  x!!!!!!!!! x            xxxyyyxxxxxx      xxxxxx                      o                x        x        ",
    " xxxx                              xxxxxxxxxx           xxxxxyy                                         x                          x       ",
    " x   y                                           xxxxxxx                        xxxxxx          xx                              o  x       ",
    " x o y                                        xxxxxxxx                                       xxxxxx                        xxyyyyyxx       ",
    " x o y   xxxx                               xxxxx                                                         xxxxxxyyyyxxx            x       ",
    " x o xxyxx        @                    xxxxxxx                                                                            x       xxx      ",
    " xxxxx          xxxxx       xxx                        o   x    xxxx   xxxxx                       f                      x     o   x      ",
    "                                   o              xx   xx                                                                  x    o   x      ",
    "                           xxx   xxxx                                                                                      x    o          ",
    "                         xxxxx            xxxxx                                                                              xxxxxxxx      ",
    "                o     xxxxxxx                                                                                                              ",
    "           xxxxxxxxxxxxxxxxxxx                                                                 xxxxxxxxxx                                  ",
    "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                                                             ",
   "                                                                                                                                             ",
   "                                                                                                                                             ",
   "                                         xxxxx                                               xxxxx                                           ",
   "                                                                                                                                             ",
   " xxxxxxxxxxxx                                               o              p                                   xxx x                         ",
   "            x                               |          xxxxxxxxxx      xxxxxxxx                |                                      x      ",
   "  o o    o  x                                   xxxxxxxx                            o       xxxxxxx     xxxxx     xxxxx                      ",
   " xxxxxx  o  x                       o o  xxxxxxxx                o o            xxxxxxxxx                                    x               ",
   "      x  o  x                      xxxxxxx                     xxxxxxx                                              xxx                      ",
   "      x                      xxxxxxx                                                                        o o o                            ",
   "      x          @      xxxxxx                                             xxxxxxx                         x x xxxx x                        ",
   "      xxxxxxx   xxxyyyxxx             xxx                                                       xxxxxx                     x                 ",
   "       xx    x                                                    xxxxx xxxxx                                                                ",
   "       xy =                xxxx                                   x         yyyy                                                             ",
   "       xy               o     x                         xxx    x              x xxx x xxx x xxxxx                                            ",
   "       xy =             o     x                                    x   o   o   x                                                   f         ",
   "       xx     xxxxxxxxxxxxxxxxx                                 xxxx xxxxx xxxxx                                                             ",
   "                                                                                                      p                                      ",
   "                        xxx                              xx                                      xxxxxxxxxx   xxx xxx                      n ",
   "                                                                                                                              o       x      ",
   "                                                                                                                        x     o    xx        ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxx!!!!!!!!"],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
